/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as docsTermsOfServiceRouteImport } from './routes/(docs)/terms-of-service'
import { Route as docsPrivacyPolicyRouteImport } from './routes/(docs)/privacy-policy'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/_auth.signup'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'
import { Route as authAuthForgotPasswordRouteImport } from './routes/(auth)/_auth.forgot-password'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const docsTermsOfServiceRoute = docsTermsOfServiceRouteImport.update({
  id: '/(docs)/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const docsPrivacyPolicyRoute = docsPrivacyPolicyRouteImport.update({
  id: '/(docs)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthForgotPasswordRoute = authAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof docsPrivacyPolicyRoute
  '/terms-of-service': typeof docsTermsOfServiceRoute
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/login': typeof authAuthLoginRoute
  '/signup': typeof authAuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof docsPrivacyPolicyRoute
  '/terms-of-service': typeof docsTermsOfServiceRoute
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/login': typeof authAuthLoginRoute
  '/signup': typeof authAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(docs)/privacy-policy': typeof docsPrivacyPolicyRoute
  '/(docs)/terms-of-service': typeof docsTermsOfServiceRoute
  '/(auth)/_auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(auth)/_auth/signup': typeof authAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/forgot-password'
    | '/login'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/forgot-password'
    | '/login'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(auth)/_auth'
    | '/(docs)/privacy-policy'
    | '/(docs)/terms-of-service'
    | '/(auth)/_auth/forgot-password'
    | '/(auth)/_auth/login'
    | '/(auth)/_auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  docsPrivacyPolicyRoute: typeof docsPrivacyPolicyRoute
  docsTermsOfServiceRoute: typeof docsTermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(docs)/terms-of-service': {
      id: '/(docs)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof docsTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(docs)/privacy-policy': {
      id: '/(docs)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof docsPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth/signup': {
      id: '/(auth)/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/forgot-password': {
      id: '/(auth)/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthForgotPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthForgotPasswordRoute: typeof authAuthForgotPasswordRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthForgotPasswordRoute: authAuthForgotPasswordRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthSignupRoute: authAuthSignupRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  authAuthRoute: authAuthRouteWithChildren,
  docsPrivacyPolicyRoute: docsPrivacyPolicyRoute,
  docsTermsOfServiceRoute: docsTermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
